import pytest
from unittest.mock import patch, MagicMock
from app.services.task_service import TaskService
from app.domain.models.task import Task
import datetime

@pytest.fixture
def mock_repository():
    repo = MagicMock()
    return repo

@pytest.fixture
def task_service(mock_repository):
    return TaskService(repository=mock_repository)

@pytest.fixture
def patch_logger():
    with patch("app.services.task_service.logger") as mock_logger:
        yield mock_logger

def make_task_data(data):
    # Simulate Task model creation
    return data

def assert_response(response, expected):
    assert response['status_code'] == expected['status_code']
    assert response['body'] == expected['response_body_json']

def assert_logs(mock_logger, expected_logs):
    if expected_logs:
        for log in expected_logs if isinstance(expected_logs, list) else [expected_logs]:
            assert any(log in call.args[0] for call in mock_logger.info.call_args_list)
    else:
        assert not mock_logger.info.called

# Test Case 1: create_task_with_all_required_fields
def test_create_task_with_all_required_fields(task_service, mock_repository, patch_logger):
    task_data = {
        'description': 'Write docs for new API endpoint',
        'due_date': '2024-12-01',
        'priority': 'high',
        'title': 'Complete documentation',
        'user_name': 'johndoe'
    }
    expected_task = task_data.copy()
    expected_task['id'] = 'autogenerated'
    mock_repository.add_task.return_value = expected_task

    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, 'Creating task for user: johndoe')
        assert response['status_code'] == 201
        assert response['body'] == expected_task

# Test Case 2: create_task_missing_title
def test_create_task_missing_title(task_service, patch_logger):
    task_data = {
        'description': 'Write docs for new API endpoint',
        'due_date': '2024-12-01',
        'priority': 'high',
        'user_name': 'johndoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'title' field is required"}

# Test Case 3: create_task_missing_description
def test_create_task_missing_description(task_service, patch_logger):
    task_data = {
        'due_date': '2024-12-01',
        'priority': 'high',
        'title': 'Complete documentation',
        'user_name': 'johndoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'description' field is required"}

# Test Case 4: create_task_missing_priority
def test_create_task_missing_priority(task_service, patch_logger):
    task_data = {
        'description': 'Write docs for new API endpoint',
        'due_date': '2024-12-01',
        'title': 'Complete documentation',
        'user_name': 'johndoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'priority' field is required"}

# Test Case 5: create_task_missing_due_date
def test_create_task_missing_due_date(task_service, patch_logger):
    task_data = {
        'description': 'Write docs for new API endpoint',
        'priority': 'high',
        'title': 'Complete documentation',
        'user_name': 'johndoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'due_date' field is required"}

# Test Case 6: create_task_missing_user_name
def test_create_task_missing_user_name(task_service, patch_logger):
    task_data = {
        'description': 'Write docs for new API endpoint',
        'due_date': '2024-12-01',
        'priority': 'high',
        'title': 'Complete documentation'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'user_name' field is required"}

# Test Case 7: create_task_with_location_field
def test_create_task_with_location_field(task_service, patch_logger):
    task_data = {
        'description': 'Discuss project roadmap',
        'due_date': '2024-07-10',
        'location': 'Conference Room A',
        'priority': 'medium',
        'title': 'Team meeting',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': 'Unexpected field: location'}

# Test Case 8: create_task_with_empty_title
def test_create_task_with_empty_title(task_service, patch_logger):
    task_data = {
        'description': 'Some description',
        'due_date': '2024-07-10',
        'priority': 'low',
        'title': '',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'title' field must not be empty"}

# Test Case 9: create_task_with_empty_description
def test_create_task_with_empty_description(task_service, patch_logger):
    task_data = {
        'description': '',
        'due_date': '2024-07-10',
        'priority': 'low',
        'title': 'Some title',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'description' field must not be empty"}

# Test Case 10: create_task_with_priority_edge_cases
def test_create_task_with_priority_edge_cases(task_service, patch_logger):
    task_data = {
        'description': 'Test priority with non-standard value',
        'due_date': '2024-09-01',
        'priority': 'urgent',
        'title': 'Boundary priority task',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'priority' field must be one of ['low', 'medium', 'high']"}

# Test Case 11: create_task_with_due_date_in_past
def test_create_task_with_due_date_in_past(task_service, patch_logger):
    task_data = {
        'description': 'Should not allow due date in the past',
        'due_date': '2020-01-01',
        'priority': 'medium',
        'title': 'Past due date task',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'due_date' must not be in the past"}

# Test Case 12: create_task_with_invalid_due_date_format
def test_create_task_with_invalid_due_date_format(task_service, patch_logger):
    task_data = {
        'description': 'Test with invalid due date format',
        'due_date': '12-31-2024',
        'priority': 'high',
        'title': 'Date format test',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': "'due_date' must be in 'YYYY-MM-DD' format"}

# Test Case 13: create_task_with_long_user_name
def test_create_task_with_long_user_name(task_service, mock_repository, patch_logger):
    user_name = 'a_string_of_50_characters_aaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    task_data = {
        'description': 'Testing upper bound for user_name length',
        'due_date': '2024-12-31',
        'priority': 'medium',
        'title': 'Long user name test',
        'user_name': user_name
    }
    expected_task = task_data.copy()
    expected_task['id'] = 'autogenerated'
    mock_repository.add_task.return_value = expected_task

    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, f'Creating task for user: {user_name}')
        assert response['status_code'] == 201
        assert response['body'] == expected_task

# Test Case 14: create_task_with_additional_unexpected_field
def test_create_task_with_additional_unexpected_field(task_service, patch_logger):
    task_data = {
        'description': 'Should fail if extra field is present',
        'due_date': '2024-10-10',
        'extra_field': 'unexpected',
        'priority': 'low',
        'title': 'Unexpected field test',
        'user_name': 'janedoe'
    }
    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, [])
        assert response['status_code'] == 400
        assert response['body'] == {'error': 'Unexpected field: extra_field'}

# Test Case 15: create_task_with_min_length_fields
def test_create_task_with_min_length_fields(task_service, mock_repository, patch_logger):
    task_data = {
        'description': 'b',
        'due_date': '2024-07-01',
        'priority': 'low',
        'title': 'a',
        'user_name': 'c'
    }
    expected_task = task_data.copy()
    expected_task['id'] = 'autogenerated'
    mock_repository.add_task.return_value = expected_task

    with patch_logger as logger:
        response = task_service.create_task(task_data)
        assert_logs(logger, 'Creating task for user: c')
        assert response['status_code'] == 201
        assert response['body'] == expected_task